CC = gcc

CFLAGS  = -Os -fomit-frame-pointer -I/usr/include/SDL  -DSCALING
LDFLAGS = -lSDL -lSDL_mixer -lm -lncurses
OBJS  = src/main.o
SOURCES = $(patsubst %.o, %.c, $(OBJS))

OUTPUT= gnp

all: $(OUTPUT)

$(OUTPUT): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

clean:
	rm $(OBJS)
